### ISSUE TITLE
Not able to create reviews

### ISSUE THREAD

**Issue by roseliux** [workarea-commerce/workarea-nvy-theme#8]
**Describe the bug**
I am having problems with the version 1.1.4, which is using the workarea-reviews (3.0.10)
when  I am trying to create a review I am receiving the following exception:
`Exception: undefined local variable or method env`
I fix this monkey patch the file config/initializers/recaptcha_verify.rb
I was checking the recaptcha gem and in a newer version they fix this, maybe just by updating the gem this will be fixed. 

**To Reproduce**
1. Put the secrets for google recaptcha on secrets.yml
2. Go to a PDP of a product and create a review

**Expected behavior**
Create a review successfully.

**Workarea Setup (please complete the following information):**
 - Workarea Version: workarea (3.4.26)

**Comment by bencrouse** [comment]
We'll look into this in our upcoming sprint. Thanks for taking the time to open the issue!

**Comment by tubbo** [comment]
Hey @roseliux, I'm looking into this right now. Did you notice this problem in production/qa/staging or locally on your machine?

**Comment by roseliux** [comment]
@tubbo  I notice this on both on production and locally when I try to fix it I set the same my secrets locally.

**Comment by tubbo** [comment]
@roseliux I'm using the out-of-box credentials locally, and in my testing I can't get this to happen. I _did_ find an unrelated issue on the appended `_product_reviews.html.haml` partial for product summaries, but I wasn't able to reproduce the issue wherein I cannot make a review. I was able to both create and approve the review. Using the same versions as you, Workarea v3.4.26 and NVY Theme v1.1.4.

**Comment by roseliux** [comment]
@tubbo  mmm the review version is  workarea-reviews (3.0.10)  let me know if I can help you with another stuff

**Comment by roseliux** [comment]
![image](https://user-images.githubusercontent.com/3598290/76037496-71160d80-5f04-11ea-88fa-9dc9abe54c29.png)
@tubbo the Recaptcha error is with version recaptcha (~> 4.3.1) what version you have?

**Comment by tubbo** [comment]
@roseliux I'm using the same version(s) locally, and I can't get this to happen. How are you verifying the review is created or not? You have to approve reviews in the admin in order to have them display on the storefront. When I approved my own review, I saw it on the product page.

<img width="261" alt="Screen Shot 2020-11-10 at 1 38 37 PM" src="https://user-images.githubusercontent.com/113026/98716717-0bfb9d00-235a-11eb-8a71-94c718d57370.png">

**Comment by roseliux** [comment]
this happen so long ago, I already upgrade my workarea gems don't know if this still happens 🤔   @tubbo  let me verify and get back to you.

**Comment by tubbo** [comment]
No worries. I’m gonna close this and if it’s still an issue, post a comment here and I’ll reopen :)   
  
  
  
    
  

  
  
>
